FROM node:18-alpine as development
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=development
COPY todo-list-shareable-frontend .
RUN npm run build

WORKDIR /app/nestjs-backend

COPY ./vue-app/package*.json ./

RUN npm install

COPY todo-list-shareable-frontend .

EXPOSE 1234

CMD ["npm", "run", "serve"]
